name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Scan with SonarCloud
        run: mvn verify sonar:sonar -Dsonar.login=${{ secrets.SONARCLOUD }}
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            JAVA_HOME: ''
# We do not build for test purposes            
#      - name: Build with Maven
#        run: mvn -B package --file pom.xml
